#ifndef PROJECT_VERSION_H
#define PROJECT_VERSION_H
#define COINSORTER_VERSION_MAJOR 0
#define COINSORTER_VERSION_MINOR 1
#define COINSORTER_VERSION_PATCH 0
#define COINSORTER_VERSION_STR "0.1.0"
#endif
