name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTS=ON -DBUILD_SUPERFORCE=ON -DBUILD_UI=ON
      - name: Build
        run: cmake --build build --parallel
      - name: Run tests
        run: ctest --test-dir build --output-on-failure
      - name: Install
        run: sudo cmake --install build --prefix /usr/local
